package teste;

import net.sourceforge.jFuzzyLogic.FIS;

public class TestMIFM {

	public static void main(String[] args) {

	    FIS fb = FIS.load("Maintainability.fcl", true);

	    fb.setVariable("NF", 12);	fb.setVariable("NM", 3);	fb.setVariable("NTop", 3);		fb.setVariable("NLeaf", 6);		fb.setVariable("DTMax", 4);		fb.setVariable("CogC", 2);		fb.setVariable("FEX", 7);		fb.setVariable("FoC", 0.25);		fb.setVariable("SCDF", 1);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 1);		fb.setVariable("RoV", 1.625);		fb.setVariable("NVC", 18);		fb.setVariable("NGOr", 0);		fb.setVariable("NGXOr", 2);		fb.evaluate();		System.out.println("Telecommunication System: " + fb.getVariable("MIFM").getValue());
	    fb.setVariable("NF", 26);	fb.setVariable("NM", 3);	fb.setVariable("NTop", 5);		fb.setVariable("NLeaf", 18);	fb.setVariable("DTMax", 4);		fb.setVariable("CogC", 6);		fb.setVariable("FEX", 18);		fb.setVariable("FoC", 0.15);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2.214);		fb.setVariable("NVC", 1400);	fb.setVariable("NGOr", 0);		fb.setVariable("NGXOr", 6);		fb.evaluate();		System.out.println("Heroku: " + fb.getVariable("MIFM").getValue());
	    fb.setVariable("NF", 33);	fb.setVariable("NM", 13);	fb.setVariable("NTop", 3);		fb.setVariable("NLeaf", 25);	fb.setVariable("DTMax", 4);		fb.setVariable("CogC", 2);		fb.setVariable("FEX", 28);		fb.setVariable("FoC", 0.27);		fb.setVariable("SCDF", 3);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 2.666);	fb.setVariable("RoV", 3.4);			fb.setVariable("NVC", 1792);	fb.setVariable("NGOr", 0);		fb.setVariable("NGXOr", 2);		fb.evaluate();		System.out.println("Jetbrains: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 29);	fb.setVariable("NM", 9);	fb.setVariable("NTop", 8);		fb.setVariable("NLeaf", 19);	fb.setVariable("DTMax", 4);		fb.setVariable("CogC", 5);		fb.setVariable("FEX", 22);		fb.setVariable("FoC", 0.20);		fb.setVariable("SCDF", 2);		fb.setVariable("MCDF", 1);		fb.setVariable("RDen", 1);		fb.setVariable("RoV", 2.2);			fb.setVariable("NVC", 3276);	fb.setVariable("NGOr", 2);		fb.setVariable("NGXOr", 3);		fb.evaluate();		System.out.println("VR application: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 37);	fb.setVariable("NM", 20);	fb.setVariable("NTop", 10);		fb.setVariable("NLeaf", 26);	fb.setVariable("DTMax", 3);		fb.setVariable("CogC", 2);		fb.setVariable("FEX", 26);		fb.setVariable("FoC", 0.21);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2.92);		fb.setVariable("NVC", 2028096);	fb.setVariable("NGOr", 2);		fb.setVariable("NGXOr", 0);		fb.evaluate();		System.out.println("Agent Illustration System: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 11);	fb.setVariable("NM", 2);	fb.setVariable("NTop", 3);		fb.setVariable("NLeaf", 7);		fb.setVariable("DTMax", 3);		fb.setVariable("CogC", 3);		fb.setVariable("FEX", 9);		fb.setVariable("FoC", 0.09);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 2);		fb.setVariable("RDen", 1);		fb.setVariable("RoV", 1.857);		fb.setVariable("NVC", 44);		fb.setVariable("NGOr", 2);		fb.setVariable("NGXOr", 1);		fb.evaluate();		System.out.println("Weather Station: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 10);	fb.setVariable("NM", 3);	fb.setVariable("NTop", 4);		fb.setVariable("NLeaf", 7);		fb.setVariable("DTMax", 3);		fb.setVariable("CogC", 2);		fb.setVariable("FEX", 7);		fb.setVariable("FoC", 0.1);			fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2.2);			fb.setVariable("NVC", 28);		fb.setVariable("NGOr", 1);		fb.setVariable("NGXOr", 1);		fb.evaluate();		System.out.println("Mobile Tourist Planner: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 15);	fb.setVariable("NM", 12);	fb.setVariable("NTop", 6);		fb.setVariable("NLeaf", 7);		fb.setVariable("DTMax", 3);		fb.setVariable("CogC", 0);		fb.setVariable("FEX", 7);		fb.setVariable("FoC", 0.13);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 1.75);		fb.setVariable("NVC", 4);		fb.setVariable("NGOr", 0);		fb.setVariable("NGXOr", 0);		fb.evaluate();		System.out.println("iNavBasic: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 23);	fb.setVariable("NM", 5);	fb.setVariable("NTop", 5);		fb.setVariable("NLeaf", 17);	fb.setVariable("DTMax", 3);		fb.setVariable("CogC", 5);		fb.setVariable("FEX", 21);		fb.setVariable("FoC", 0);			fb.setVariable("SCDF", 2);		fb.setVariable("MCDF", 2);		fb.setVariable("RDen", 1);		fb.setVariable("RoV", 2.45);		fb.setVariable("NVC", 4774);	fb.setVariable("NGOr", 3);		fb.setVariable("NGXOr", 2);		fb.evaluate();		System.out.println("Student Attendance System: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 18);	fb.setVariable("NM", 1);	fb.setVariable("NTop", 1);		fb.setVariable("NLeaf", 13);	fb.setVariable("DTMax", 5);		fb.setVariable("CogC", 4);		fb.setVariable("FEX", 13);		fb.setVariable("FoC", 0);			fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2.33);		fb.setVariable("NVC", 8191);	fb.setVariable("NGOr", 4);		fb.setVariable("NGXOr", 0);		fb.evaluate();		System.out.println("Amazon web services: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 43);	fb.setVariable("NM", 13);	fb.setVariable("NTop", 9);		fb.setVariable("NLeaf", 28);	fb.setVariable("DTMax", 5);		fb.setVariable("CogC", 10);		fb.setVariable("FEX", 33);		fb.setVariable("FoC", 0.04);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 5);		fb.setVariable("RDen", 0.6);	fb.setVariable("RoV", 2.08);		fb.setVariable("NVC", 1202985);	fb.setVariable("NGOr", 10);		fb.setVariable("NGXOr", 0);		fb.evaluate();		System.out.println("Tree Stem Deformation Simulator: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 43);	fb.setVariable("NM", 22);	fb.setVariable("NTop", 3);		fb.setVariable("NLeaf", 32);	fb.setVariable("DTMax", 4);		fb.setVariable("CogC", 5);		fb.setVariable("FEX", 32);		fb.setVariable("FoC", 0.13);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2.93);		fb.setVariable("NVC", 23040);	fb.setVariable("NGOr", 4);		fb.setVariable("NGXOr", 1);		fb.evaluate();		System.out.println("Emergency Response Application: " + fb.getVariable("MIFM").getValue());																																																																																																																																																																																																																											
		fb.setVariable("NF", 20);	fb.setVariable("NM", 13);	fb.setVariable("NTop", 1);		fb.setVariable("NLeaf", 14);	fb.setVariable("DTMax", 3);		fb.setVariable("CogC", 0);		fb.setVariable("FEX", 14);		fb.setVariable("FoC", 0.3);			fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 3.16);		fb.setVariable("NVC", 64);		fb.setVariable("NGOr", 0);		fb.setVariable("NGXOr", 0);		fb.evaluate();		System.out.println("Voice Recording System: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 11);	fb.setVariable("NM", 3);	fb.setVariable("NTop", 4);		fb.setVariable("NLeaf", 7);		fb.setVariable("DTMax", 3);		fb.setVariable("CogC", 1);		fb.setVariable("FEX", 7);		fb.setVariable("FoC", 0.363);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2.2);			fb.setVariable("NVC", 21);		fb.setVariable("NGOr", 0);		fb.setVariable("NGXOr", 1);		fb.evaluate();		System.out.println("Poker Game: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 21);	fb.setVariable("NM", 4);	fb.setVariable("NTop", 4);		fb.setVariable("NLeaf", 14);	fb.setVariable("DTMax", 5);		fb.setVariable("CogC", 5);		fb.setVariable("FEX", 20);		fb.setVariable("FoC", 0.95);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 6);		fb.setVariable("RDen", 1);		fb.setVariable("RoV", 2.08);		fb.setVariable("NVC", 4774);	fb.setVariable("NGOr", 5);		fb.setVariable("NGXOr", 0);		fb.evaluate();		System.out.println("Card Payment Terminal: " + fb.getVariable("MIFM").getValue());																																																																																																																					
		fb.setVariable("NF", 11);	fb.setVariable("NM", 3);	fb.setVariable("NTop", 1);		fb.setVariable("NLeaf", 7);		fb.setVariable("DTMax", 4);		fb.setVariable("CogC", 2);		fb.setVariable("FEX", 7);		fb.setVariable("FoC", 0);			fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2);			fb.setVariable("NVC", 10);		fb.setVariable("NGOr", 0);		fb.setVariable("NGXOr", 2);		fb.evaluate();		System.out.println("ESCA Embeeded System: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 14);	fb.setVariable("NM", 2);	fb.setVariable("NTop", 2);		fb.setVariable("NLeaf", 11);	fb.setVariable("DTMax", 3);		fb.setVariable("CogC", 2);		fb.setVariable("FEX", 11);		fb.setVariable("FoC", 0);			fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 3);			fb.setVariable("NVC", 1905);	fb.setVariable("NGOr", 2);		fb.setVariable("NGXOr", 0);		fb.evaluate();		System.out.println("Simple Drawing Tools: " + fb.getVariable("MIFM").getValue());	
		fb.setVariable("NF", 15);	fb.setVariable("NM", 3);	fb.setVariable("NTop", 9);		fb.setVariable("NLeaf", 12);	fb.setVariable("DTMax", 4);		fb.setVariable("CogC", 6);		fb.setVariable("FEX", 12);		fb.setVariable("FoC", 0.2);			fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2.22);		fb.setVariable("NVC", 44);		fb.setVariable("NGOr", 4);		fb.setVariable("NGXOr", 2);		fb.evaluate();		System.out.println("VMS: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 29);	fb.setVariable("NM", 18);	fb.setVariable("NTop", 9);		fb.setVariable("NLeaf", 20);	fb.setVariable("DTMax", 4);		fb.setVariable("CogC", 3);		fb.setVariable("FEX", 20);		fb.setVariable("FoC", 0.13);		fb.setVariable("SCDF", 0);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 0);		fb.setVariable("RoV", 2.58);		fb.setVariable("NVC", 360);		fb.setVariable("NGOr", 3);		fb.setVariable("NGXOr", 0);		fb.evaluate();		System.out.println("SWAMP Platform: " + fb.getVariable("MIFM").getValue());
		fb.setVariable("NF", 34);	fb.setVariable("NM", 5);	fb.setVariable("NTop", 7);		fb.setVariable("NLeaf", 24);	fb.setVariable("DTMax", 5);		fb.setVariable("CogC", 8);		fb.setVariable("FEX", 26);		fb.setVariable("FoC", 0.11);		fb.setVariable("SCDF", 2);		fb.setVariable("MCDF", 0);		fb.setVariable("RDen", 1);		fb.setVariable("RoV", 2.27);		fb.setVariable("NVC", 267840);	fb.setVariable("NGOr", 3);		fb.setVariable("NGXOr", 5);		fb.evaluate();		System.out.println("Text To Speech App: " + fb.getVariable("MIFM").getValue());

		System.out.println("Mobile Game: " + fb.getVariable("MIFM").getValue());

	}

}

